   # Introdução à Ciência de Dados - UFPB - Exercício Numpy.
   # Professor: Yuri Malheiros - Aluno: Vinícius Vieri Bezerra de Lima.

NumPy

# Questão 1

Implemente a função distance abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, p1 = np.array([2,4]) representa o ponto com coordenadas x=2 e y=2.

import numpy as np

    def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    *>>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903*
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

In [ ]:
import numpy as np 
import math
from math import sqrt

**Primeiro, temos que saber o que exatamente é uma distância euclidiana**



#### distancia euclidiana == raizquadrada(x2 - x1)^2 + (y2 - y1)^2

#### na primeira, decidi usar uma distância feita mais 'manualmente'

#### temos então, a forma de calculá-la.
    
#### sqrt( (p2[0] - p1[0])**2 + (p2[1] - p1[1])**2 )

In [ ]:
def distance(p1, p2):
    euclidian_distance = sqrt( (p2[0] - p1[0])**2 + (p2[1] - p1[1])**2 )
    return euclidian_distance

In [ ]:
distance(np.array([0,0]), np.array([1,1]))

In [ ]:
distance(np.array([1,2]), np.array([3,4]))

In [ ]:
distance(np.array([5,2]), np.array([-2,-1]))

# Questão 2

Implemente a função n_distances abaixo. Ela recebe um ponto (p1), como um array do NumPy, e uma lista de pontos (points), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de p1 para todos os pontos da matriz points. O retorno também é uma matriz, onde cada linha tem a distância de p1 para o ponto daquela linha.

def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    

### Nesta questão estarei utilizando a math.dist da biblioteca math para calcular a distância euclidiana.
### Ou seja, tentei equilibrar algo mais manual com algo mais rápido.

In [ ]:
def n_distances(p1, points):
    euclidian_distance = np.zeros(len(points))
    for i in range(len(points)):
        euclidian_distance[i] = (math.dist(p1, points[i]))
    return euclidian_distance

In [ ]:
n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))

In [ ]:
n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))